### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by 6ooo** [ObamaAteMyKids/CombatMasterHack#1]
Sadly, the game is crashing after being few seconds ingame

Ive only use esp

**Comment by 6ooo** [comment]
Also  ive managed to get the aimbot work in bot lobby, but in online multiplayer the aimbot does not work aka, aims at the enemy but buggy and just shoots forward.

How could i make it work in multiplayer

**Comment by ObamaAteMyKids** [comment]
The esp crashes because it tries displaying their active weapon for example even when it doesnt exist, its an easy fix. The aimbot doesnt work online because it sets ur camera transform back to the server camera transform  u just need to set it to angles that dont get overridden by the server

**Comment by ObamaAteMyKids** [comment]
hubert#0334
